# we want to use SAUL:
USEMODULE += saul_default
# include the shell:
USEMODULE += shell_cmds_default
# additional modules for debugging:
USEMODULE += ps

# BME280 connected via I2C
USEMODULE += bme280_i2c
# When using I2C, specify the default I2C device to use,
# and the BME280's address (see datasheet).
# The values below are the defaults:

CFLAGS += -DBMX280_PARAM_I2C_DEV="I2C_DEV(0)"
CFLAGS += -DBMX280_PARAM_I2C_ADDR=0x77

# include $(RIOTBASE)/Makefile.include
