var searchData=
[
  ['saul_5futils_2eh_0',['saul_utils.h',['../saul__utils_8h.html',1,'']]],
  ['setup_1',['setup',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2Dongle_2gnrc__border__router_2README.html#autotoc_md4',1,'Setup'],['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2Dongle_2gnrc__border__router_2README.html#autotoc_md8',1,'Setup']]],
  ['setup_20instructions_20strong_2',['🚀 &lt;strong&gt;Setup Instructions&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md33',1,'']]],
  ['sharing_20with_20host_3',['Connection sharing with host',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2Dongle_2gnrc__border__router_2README.html#autotoc_md2',1,'']]],
  ['shell_5fcommand_5futils_2ec_4',['shell_command_utils.c',['../shell__command__utils_8c.html',1,'']]],
  ['simulated_20network_20with_20native_5',['Simulated network with native',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2Dongle_2gnrc__border__router_2README.html#autotoc_md6',1,'']]],
  ['slip_6',['gnrc_networking_border_router with SLIP',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2Dongle_2gnrc__border__router_2README.html#autotoc_md10',1,'']]],
  ['software_3a_20strong_7',['&lt;strong&gt;Software:&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md28',1,'']]],
  ['strong_201_20flashing_20the_20dk_20strong_8',['&lt;strong&gt;1. Flashing the DK&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md34',1,'']]],
  ['strong_202_20flashing_20the_20dongle_20strong_9',['&lt;strong&gt;2. Flashing the Dongle&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md35',1,'']]],
  ['strong_203_20the_20mqtt_20broker_20on_20aws_20ec2_20strong_10',['&lt;strong&gt;3. The MQTT Broker on AWS EC2&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md36',1,'']]],
  ['strong_204_20the_20mqtt_20broker_20on_20aws_20iot_20core_20strong_11',['&lt;strong&gt;4. The MQTT Broker on AWS IoT Core&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md37',1,'']]],
  ['strong_206_20the_20aws_20api_20gateaway_20strong_12',['&lt;strong&gt;6. The AWS API Gateaway&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md39',1,'']]],
  ['strong_207_20the_20webhook_20strong_13',['&lt;strong&gt;7. The Webhook&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md40',1,'']]],
  ['strong_208_20telegram_20bot_20strong_14',['&lt;strong&gt;8. Telegram Bot&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md41',1,'']]],
  ['strong_20certificates_20and_20keys_3a_20strong_15',['&lt;strong&gt;Certificates and Keys:&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md29',1,'']]],
  ['strong_20components_3a_20strong_16',['&lt;strong&gt;Components:&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md22',1,'']]],
  ['strong_20contact_20strong_17',['👨‍💻 &lt;strong&gt;Contact&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md43',1,'']]],
  ['strong_20documentation_20strong_18',['📖 &lt;strong&gt;Documentation&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md42',1,'']]],
  ['strong_20features_20strong_19',['✨ &lt;strong&gt;Features&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md24',1,'']]],
  ['strong_20hardware_3a_20strong_20',['&lt;strong&gt;Hardware:&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md27',1,'']]],
  ['strong_20project_20overview_20strong_21',['📜 &lt;strong&gt;Project Overview&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md19',1,'']]],
  ['strong_20project_20structure_20strong_22',['📂 &lt;strong&gt;Project structure&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md32',1,'']]],
  ['strong_20requirements_20strong_23',['🛠️ &lt;strong&gt;Requirements&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md26',1,'']]],
  ['strong_20setup_20instructions_20strong_24',['🚀 &lt;strong&gt;Setup Instructions&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md33',1,'']]],
  ['strong_20software_3a_20strong_25',['&lt;strong&gt;Software:&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md28',1,'']]],
  ['strong_20system_20architecture_20strong_26',['📐 &lt;strong&gt;System Architecture&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md21',1,'']]],
  ['strong_20table_20of_20contents_20strong_27',['📚 &lt;strong&gt;Table of Contents&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md17',1,'']]],
  ['strong_20telegram_20bot_3a_20strong_20allows_20interaction_20with_20the_20iot_20system_28',['9. &lt;strong&gt;Telegram Bot:&lt;/strong&gt; Allows interaction with the IoT system.',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md23',1,'']]],
  ['strong_20textyouriotdevice_20strong_29',['🌐 &lt;strong&gt;TextYourIoTDevice&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html',1,'']]],
  ['strong_20tools_3a_20strong_30',['&lt;strong&gt;Tools:&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md30',1,'']]],
  ['structure_20strong_31',['📂 &lt;strong&gt;Project structure&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md32',1,'']]],
  ['system_32',['9. &lt;strong&gt;Telegram Bot:&lt;/strong&gt; Allows interaction with the IoT system.',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md23',1,'']]],
  ['system_20architecture_20strong_33',['📐 &lt;strong&gt;System Architecture&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md21',1,'']]]
];
