var searchData=
[
  ['certificates_0',['certificates',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md41',1,'+ &lt;strong&gt;Solution:&lt;/strong&gt; Verify the broker IP and TLS certificates.'],['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md46',1,'+ &lt;strong&gt;Solution:&lt;/strong&gt; Verify the broker IP and TLS certificates.']]],
  ['certificates_20and_20keys_3a_20strong_1',['&lt;strong&gt;Certificates and Keys:&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md29',1,'']]],
  ['check_20the_20mosquitto_20configuration_20and_20aws_20iot_20policies_2',['check the mosquitto configuration and aws iot policies',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md42',1,'- &lt;strong&gt;Solution:&lt;/strong&gt; Check the Mosquitto configuration and AWS IoT policies.'],['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md47',1,'- &lt;strong&gt;Solution:&lt;/strong&gt; Check the Mosquitto configuration and AWS IoT policies.']]],
  ['cloudwatch_3',['Implement logging for debugging and monitoring IoT devices using AWS CloudWatch',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md25',1,'']]],
  ['components_3a_20strong_4',['&lt;strong&gt;Components:&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md22',1,'']]],
  ['config_5',['gnrc_border_router with manual config',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2Dongle_2gnrc__border__router_2README.html#autotoc_md7',1,'']]],
  ['configuration_6',['configuration',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2Dongle_2gnrc__border__router_2README.html#autotoc_md12',1,'Configuration'],['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2Dongle_2gnrc__border__router_2README.html',1,'gnrc_border_router using automatic configuration']]],
  ['configuration_20and_20aws_20iot_20policies_7',['configuration and aws iot policies',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md42',1,'- &lt;strong&gt;Solution:&lt;/strong&gt; Check the Mosquitto configuration and AWS IoT policies.'],['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md47',1,'- &lt;strong&gt;Solution:&lt;/strong&gt; Check the Mosquitto configuration and AWS IoT policies.']]],
  ['connect_20app_3a_20for_20flashing_20the_20firmware_20in_20dongle_8',['- nRF Desktop Connect APP: For flashing the firmware in Dongle',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md31',1,'']]],
  ['connection_20sharing_20with_20host_9',['Connection sharing with host',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2Dongle_2gnrc__border__router_2README.html#autotoc_md2',1,'']]],
  ['contents_20strong_10',['📚 &lt;strong&gt;Table of Contents&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md17',1,'']]],
  ['core_20strong_11',['&lt;strong&gt;4. The MQTT Broker on AWS IoT Core&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md37',1,'']]]
];
