var searchData=
[
  ['table_20of_20contents_20strong_0',['📚 &lt;strong&gt;Table of Contents&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md17',1,'']]],
  ['telegram_20bot_20strong_1',['&lt;strong&gt;5. Telegram Bot&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md38',1,'']]],
  ['telegram_20bot_3a_20strong_20allows_20interaction_20with_20the_20iot_20system_2',['9. &lt;strong&gt;Telegram Bot:&lt;/strong&gt; Allows interaction with the IoT system.',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md23',1,'']]],
  ['testing_20the_20system_20strong_3',['testing the system strong',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md39',1,'🔬 &lt;strong&gt;Testing the System&lt;/strong&gt;'],['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md44',1,'🔬 &lt;strong&gt;Testing the System&lt;/strong&gt;']]],
  ['textyouriotdevice_20strong_4',['🌐 &lt;strong&gt;TextYourIoTDevice&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html',1,'']]],
  ['the_20broker_20ip_20and_20tls_20certificates_5',['the broker ip and tls certificates',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md46',1,'+ &lt;strong&gt;Solution:&lt;/strong&gt; Verify the broker IP and TLS certificates.'],['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md41',1,'+ &lt;strong&gt;Solution:&lt;/strong&gt; Verify the broker IP and TLS certificates.']]],
  ['the_20dk_20strong_6',['&lt;strong&gt;1. Flashing the DK&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md34',1,'']]],
  ['the_20dongle_20strong_7',['&lt;strong&gt;2. Flashing the Dongle&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md35',1,'']]],
  ['the_20firmware_20in_20dongle_8',['- nRF Desktop Connect APP: For flashing the firmware in Dongle',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md31',1,'']]],
  ['the_20iot_20system_9',['9. &lt;strong&gt;Telegram Bot:&lt;/strong&gt; Allows interaction with the IoT system.',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md23',1,'']]],
  ['the_20mosquitto_20configuration_20and_20aws_20iot_20policies_10',['the mosquitto configuration and aws iot policies',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md42',1,'- &lt;strong&gt;Solution:&lt;/strong&gt; Check the Mosquitto configuration and AWS IoT policies.'],['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md47',1,'- &lt;strong&gt;Solution:&lt;/strong&gt; Check the Mosquitto configuration and AWS IoT policies.']]],
  ['the_20mqtt_20broker_20on_20aws_20ec2_20strong_11',['&lt;strong&gt;3. The MQTT Broker on AWS EC2&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md36',1,'']]],
  ['the_20mqtt_20broker_20on_20aws_20iot_20core_20strong_12',['&lt;strong&gt;4. The MQTT Broker on AWS IoT Core&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md37',1,'']]],
  ['the_20system_20strong_13',['the system strong',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md39',1,'🔬 &lt;strong&gt;Testing the System&lt;/strong&gt;'],['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md44',1,'🔬 &lt;strong&gt;Testing the System&lt;/strong&gt;']]],
  ['tls_20certificates_14',['tls certificates',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md41',1,'+ &lt;strong&gt;Solution:&lt;/strong&gt; Verify the broker IP and TLS certificates.'],['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md46',1,'+ &lt;strong&gt;Solution:&lt;/strong&gt; Verify the broker IP and TLS certificates.']]],
  ['tools_3a_20strong_15',['&lt;strong&gt;Tools:&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md30',1,'']]],
  ['troubleshooting_20strong_16',['troubleshooting strong',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md40',1,'🛠️ &lt;strong&gt;Troubleshooting&lt;/strong&gt;'],['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md45',1,'🛠️ &lt;strong&gt;Troubleshooting&lt;/strong&gt;']]]
];
