var searchData=
[
  ['address_20of_20dongle_0',['IPv6 address of Dongle',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2Dongle_2ip-address__dongle.html',1,'']]],
  ['allows_20interaction_20with_20the_20iot_20system_1',['9. &lt;strong&gt;Telegram Bot:&lt;/strong&gt; Allows interaction with the IoT system.',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md23',1,'']]],
  ['and_20aws_20iot_20policies_2',['and aws iot policies',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md42',1,'- &lt;strong&gt;Solution:&lt;/strong&gt; Check the Mosquitto configuration and AWS IoT policies.'],['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md47',1,'- &lt;strong&gt;Solution:&lt;/strong&gt; Check the Mosquitto configuration and AWS IoT policies.']]],
  ['and_20keys_3a_20strong_3',['&lt;strong&gt;Certificates and Keys:&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md29',1,'']]],
  ['and_20monitoring_20iot_20devices_20using_20aws_20cloudwatch_4',['Implement logging for debugging and monitoring IoT devices using AWS CloudWatch',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md25',1,'']]],
  ['and_20tls_20certificates_5',['and tls certificates',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md41',1,'+ &lt;strong&gt;Solution:&lt;/strong&gt; Verify the broker IP and TLS certificates.'],['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md46',1,'+ &lt;strong&gt;Solution:&lt;/strong&gt; Verify the broker IP and TLS certificates.']]],
  ['app_3a_20for_20flashing_20the_20firmware_20in_20dongle_6',['- nRF Desktop Connect APP: For flashing the firmware in Dongle',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md31',1,'']]],
  ['architecture_20strong_7',['📐 &lt;strong&gt;System Architecture&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md21',1,'']]],
  ['automatic_20configuration_8',['gnrc_border_router using automatic configuration',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2Dongle_2gnrc__border__router_2README.html',1,'']]],
  ['aws_20cloudwatch_9',['Implement logging for debugging and monitoring IoT devices using AWS CloudWatch',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md25',1,'']]],
  ['aws_20ec2_20strong_10',['&lt;strong&gt;3. The MQTT Broker on AWS EC2&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md36',1,'']]],
  ['aws_20iot_20core_20strong_11',['&lt;strong&gt;4. The MQTT Broker on AWS IoT Core&lt;/strong&gt;',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md37',1,'']]],
  ['aws_20iot_20policies_12',['aws iot policies',['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md42',1,'- &lt;strong&gt;Solution:&lt;/strong&gt; Check the Mosquitto configuration and AWS IoT policies.'],['../md__2home_2mj_2Desktop_2IoT-Chat-Digitalization_2README.html#autotoc_md47',1,'- &lt;strong&gt;Solution:&lt;/strong&gt; Check the Mosquitto configuration and AWS IoT policies.']]]
];
